### ISSUE TITLE
echarts 设置windth:100%不生效问题

### ISSUE THREAD

**Issue by azhengyongqin** [ecomfe/vue-echarts#367]
## The type of this issue / Issue 类型

- [x] Bug report / Bug 报告
- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。
- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### echarts 设置windth:100%不生效

```html
<div class="charts-contrainer">
      <v-chart :auto-resize="true" :options="polar"></v-chart>
</div>
```
```css
.charts-contrainer {
  margin: 15px;
  height: 334px;
  width: 300px;
  background-color: white;

  .echarts {
    width: 100%;
    height: 100%;
  }
}
```

![image](https://user-images.githubusercontent.com/18138282/62148656-b77f0a80-b32c-11e9-8341-957390b7db1c.png)

### 可以看到父容器宽高已经生效
![image](https://user-images.githubusercontent.com/18138282/62148738-e09f9b00-b32c-11e9-800e-05817977addc.png)

### echarts 的宽高也已经生效
![image](https://user-images.githubusercontent.com/18138282/62148782-f745f200-b32c-11e9-9d1a-b51a3d9142e6.png)

### 但是 echarts下层的div 的宽高一直是 100px; 当我设置 echarts的withd:200%, 这里就变成了200px;
![image](https://user-images.githubusercontent.com/18138282/62148930-3b38f700-b32d-11e9-892c-7e23a01d09a7.png)
